Repository cytomine/cytomine, pull requests merged in 2025-09, with the labels that each got.

#114 fix: pims signature
  pims/pims/api/utils/cytomine_auth.py
Labels: bug

#121 chore: remove debug logging
  pims/pims/api/operations.py
Labels: chore

#129 fix: python client ci
  .github/workflows/client-python-code-quality.yaml
  .github/workflows/client-python.yaml
  clients/python/.github/release.yaml
  clients/python/.gitignore
  clients/python/.gitlab-ci.yml
  clients/python/.pylintrc
  clients/python/Dockerfile
  clients/python/cytomine/__init__.py
  clients/python/cytomine/models/__init__.py
  clients/python/cytomine/models/_utilities/__init__.py
  clients/python/examples/add_user.py
  clients/python/examples/delete_annotations.py
  clients/python/examples/get_annotations_bbox.py
  clients/python/examples/test.py
  clients/python/examples/upload_image.py
  clients/python/pyproject.toml
  clients/python/requirements.txt
  clients/python/setup.py
  clients/python/uv.lock
Labels: bug, ci/cd

#137 ci: publish python client to pypi
  .github/workflows/client-python.yaml
Labels: ci/cd

#144 refactor: dev inside Docker container
  .gitignore
  Makefile
  cytomine-community-edition/cytomine-dev
  cytomine-community-edition/docker/docker-compose.override.ae.yaml
  cytomine-community-edition/docker/docker-compose.override.cbir.yaml
  cytomine-community-edition/docker/docker-compose.override.core.yaml
  cytomine-community-edition/docker/docker-compose.override.iam.yaml
  cytomine-community-edition/docker/docker-compose.override.ims.yaml
  cytomine-community-edition/docker/docker-compose.override.main.yaml
  cytomine-community-edition/docker/docker-compose.override.sam.yaml
  cytomine-community-edition/docker/docker-compose.override.ui.yaml
  cytomine-community-edition/scripts/compose.sh
  cytomine-community-edition/scripts/get-profile.sh
  cytomine-community-edition/scripts/set-profile.sh
  docker/compose.dev.ae.yaml
  docker/compose.dev.cbir.yaml
  docker/compose.dev.core.yaml
  docker/compose.dev.iam.yaml
  docker/compose.dev.ims.yaml
  docker/compose.dev.sam.yaml
  docker/compose.dev.ui.yaml
  iam/Dockerfile
Labels: enhancement

#150 docs: add Kubernetes installation guide
  docs/src/.vuepress/site-config/navbar.js
  docs/src/.vuepress/site-config/sidebar.js
  docs/src/admin-guide/k8s/installation.md
Labels: documentation

#161 84 add api to configure appstore in cytomine
  app-engine/src/main/java/be/cytomine/appengine/controllers/AppStoreController.java
  app-engine/src/main/java/be/cytomine/appengine/dto/responses/errors/ErrorCode.java
  app-engine/src/main/java/be/cytomine/appengine/dto/responses/errors/ErrorDefinitions.java
  app-engine/src/main/java/be/cytomine/appengine/exceptions/AppStoreAlreadyExistsException.java
  app-engine/src/main/java/be/cytomine/appengine/exceptions/AppStoreNotFoundException.java
  app-engine/src/main/java/be/cytomine/appengine/exceptions/AppStoreValidationException.java
  app-engine/src/main/java/be/cytomine/appengine/exceptions/handlers/AppStoreApiExceptionHandler.java
  app-engine/src/main/java/be/cytomine/appengine/models/store/AppStore.java
  app-engine/src/main/java/be/cytomine/appengine/repositories/AppStoreRepository.java
  app-engine/src/main/java/be/cytomine/appengine/services/AppStoreService.java
  app-engine/src/test/java/be/cytomine/appengine/unit/services/AppStoreServiceTest.java
Labels: enhancement, service/app-engine

#164 fix: DICOM spacing between slices attribute parsing
  pims/plugins/pims-plugin-format-dicom/pims_plugin_format_dicom/dicom.py
Labels: bug

#173 docs: add upgrade instruction
  docs/src/admin-guide/ce/installation.md
Labels: documentation

#196 feat: install app from web-ui app store
  app-engine/src/main/java/be/cytomine/appengine/models/store/AppStore.java
  app-engine/src/main/java/be/cytomine/appengine/services/AppStoreService.java
  core/src/main/java/be/cytomine/controller/appengine/RestTaskController.java
  core/src/main/java/be/cytomine/controller/appengine/StoreController.java
  web-ui/ui/src/components/appengine/AppCard.vue
  web-ui/ui/src/components/appengine/AppConfigurationPage.vue
  web-ui/ui/src/components/appengine/AppLocalPage.vue
  web-ui/ui/src/components/appengine/AppStoreAddModal.vue
  web-ui/ui/src/components/appengine/AppStorePage.vue
  web-ui/ui/src/locales/translations.csv
  web-ui/ui/tests/unit/components/appengine/AppCard.test.js
  web-ui/ui/tests/unit/components/appengine/AppLocalPage.test.js
  web-ui/ui/tests/unit/components/appengine/AppStoreAddModal.test.js
  web-ui/ui/tests/unit/components/appengine/AppStorePage.test.js
Labels: enhancement

#201 chore: remove unused env variables
  compose.yaml
  core/src/main/java/be/cytomine/service/database/BootstrapDataService.java
Labels: chore

#200 feat(web-ui): read app info from store
  core/src/main/java/be/cytomine/controller/appengine/RestTaskController.java
  core/src/main/java/be/cytomine/controller/appengine/StoreController.java
  web-ui/ui/meta-prefixes.json
  web-ui/ui/src/components/appengine/AppCard.vue
  web-ui/ui/src/components/appengine/AppConfigurationPage.vue
  web-ui/ui/src/components/appengine/AppInfoPage.vue
  web-ui/ui/src/components/appengine/AppLayout.vue
  web-ui/ui/src/components/appengine/AppStorePage.vue
  web-ui/ui/src/utils/appengine/task.js
  web-ui/ui/tests/unit/components/appengine/AppCard.test.js
  web-ui/ui/tests/unit/components/appengine/AppConfigurationPage.test.js
  web-ui/ui/tests/unit/components/appengine/AppLayout.test.js
  web-ui/ui/tests/unit/components/appengine/AppStorePage.test.js
Labels: enhancement

#206 docs: update Docker Compose installation procedure
  docs/src/.vuepress/public/images/admin-guide/ce/cytomine-2025.1-overview.svg
  docs/src/.vuepress/site-config/navbar.js
  docs/src/.vuepress/site-config/sidebar.js
  docs/src/admin-guide/ce/installation.md
  docs/src/admin-guide/clusters/README.md
  docs/src/admin-guide/clusters/microk8s/README.md
  docs/src/admin-guide/clusters/microk8s/configuration.md
  docs/src/admin-guide/clusters/microk8s/installation.md
  docs/src/admin-guide/clusters/microk8s/troubleshooting.md
  docs/src/admin-guide/clusters/microk8s/uninstallation.md
Labels: documentation

#208 chore: remove deprecated algo annotation
  core/specs/openapi.yml
  core/src/main/java/be/cytomine/controller/ontology/RestAlgoAnnotationController.java
  core/src/main/java/be/cytomine/controller/ontology/RestAnnotationDomainController.java
  core/src/main/java/be/cytomine/controller/ontology/RestAnnotationTermController.java
  core/src/main/java/be/cytomine/domain/GenericCytomineDomainContainer.java
  core/src/main/java/be/cytomine/domain/ontology/AnnotationDomain.java
  core/src/main/java/be/cytomine/service/ontology/AlgoAnnotationService.java
  core/src/main/java/be/cytomine/service/ontology/AlgoAnnotationTermService.java
  core/src/main/java/be/cytomine/service/ontology/GenericAnnotationService.java
  core/src/main/java/be/cytomine/service/project/ProjectService.java
  core/src/main/resources/messages.properties
  core/src/test/java/be/cytomine/controller/security/UserResourceTests.java
  docs/src/dev-guide/api/reference.md
  web-ui/api-client/src/collections/annotation-collection.js
  web-ui/api-client/src/models/annotation-comment.js
  web-ui/api-client/src/models/annotation.js
  web-ui/api-client/src/models/project.js
  web-ui/api-client/tests/project.test.js
  web-ui/ui/src/components/annotations/AnnotationDetails.vue
Labels: chore
