Repository cytomine/cytomine, pull requests merged in 2025-08, with the labels that each got.

#50 fix: app engine OpenAPI validation
  .github/workflows/app-engine.yaml
Labels: bug, ci/cd, service/app-engine

#49 ci: add pims test job
  .github/workflows/app-engine.yaml
  .github/workflows/cbir.yml
  .github/workflows/core.yaml
  .github/workflows/ims.yaml
  .github/workflows/installer.yaml
  .github/workflows/web-ui.yaml
  cytomine-community-edition/docker-compose.yml
  pims/Dockerfile
  pims/pims-config.env
  pims/plugins/pims-plugin-format-openslide/install-prerequisites.sh
  pims/tests/conftest.py
  pims/tests/pims-config.env
  pims/tests/test_jpeg.py
  pims/tests/test_png.py
  pims/tests/test_tiff.py
Labels: ci/cd, test, service/ims

#54 chore: build web-ui image on push
  .github/workflows/build-and-push-docker-images.yaml
  web-ui/Dockerfile
Labels: ci/cd

#68 refactor: entrypoint scripts in pims Dockerfile
  cytomine-community-edition/docker/docker-compose.override.ims.yaml
  pims/Dockerfile
Labels: refactor

#71 ci: build and push docker on pull request
  .github/workflows/pull-request.yaml
  app-engine/Dockerfile
  cbir/Dockerfile
  core/Dockerfile
  iam/Dockerfile
  mongo/Dockerfile
  nginx/Dockerfile
  pims/Dockerfile
  postgis/Dockerfile
  web-ui/Dockerfile
Labels: ci/cd

#79 refactor: add simple ping
  app-engine/build.gradle
  app-engine/src/main/java/be/cytomine/appengine/controllers/ServerController.java
  app-engine/src/test/java/be/cytomine/appengine/utils/ApiClient.java
Labels: bug

#100 ci: push to docker.io with github runners
  .github/workflows/docker.yaml
Labels: ci/cd

#108 refactor: remove host for custom-ui
  web-ui/api-client/src/cytomine.js
  web-ui/api-client/src/models/project.js
Labels: bug
